---
#-------------------------------------------------------#
# This will install only Generic Container Selinux RPM  #
#    https://github.com/containers/container-selinux    #
#-------------------------------------------------------#

########################################
#       Install Selinux Artifact       #
########################################
- name: Create SELinux artifacts folder
  ansible.builtin.file:
    path: "{{ rke2_artifact_path }}/selinux/redhat"
    state: directory
    mode: 0700

- name: Copy local Container SELinux artifacts RPM
  ansible.builtin.copy:
    src: "{{ local_rke2_selinux_path }}/redhat/{{ item | basename }}"
    dest: "{{ rke2_artifact_path }}/selinux/redhat/{{ item | basename }}"
    mode: 0644
    force: yes
  with_items: "{{ container_selinux_artifact }}"

- name: Copy local CentOS GPG-Key
  ansible.builtin.copy:
    src: "{{ local_rke2_selinux_path }}/redhat/{{ centos_gpg_key_file }}"
    dest: "{{ rke2_artifact_path }}/selinux/redhat/{{ centos_gpg_key_file }}"
    mode: 0644
    force: yes

- name: Add CentOS GPG key to the host
  rpm_key:
    state: present
    key: "{{ rke2_artifact_path }}/selinux/redhat/{{ centos_gpg_key_file }}"

- name: Find all container Selinux RPM files in SELinux folder
  find:
    paths: "{{ rke2_artifact_path }}/selinux/redhat"
    patterns: "*.rpm"
  register: rpm_files_selinux

- name: Setting rpm_list SELinux
  set_fact:
    rpm_list_selinux: "{{ rpm_files_selinux.files | map(attribute='path') | list }}"

- name: Debug the list of rpm files found
  debug:
    msg: "{{ rpm_list_selinux }}"

- name: Installing all SELinux RPM files at once
  yum:
    name: "{{ rpm_list_selinux }}"
    state: present
