---
#------------------------------------#
- name: Download Artifacts
  hosts: localhost
  roles:
    - role: artifacts

#------------------------------------#
- name: Selinux
  become: true
  hosts: k8s_cluster
  roles:
    - role: selinux
      when:
        - rke2_selinux is true

#------------------------------------#
- name: Server Configuration
  hosts: k8s_cluster
  become: true
  roles:
    - role: server-config

#------------------------------------#
- name: kube-vip
  become: true
  hosts: masters
  roles:
    - role: kube-vip
      when:
        - kube_vip | bool

#------------------------------------#
- name: Find Active Server
  become: true
  hosts: k8s_cluster
  roles:
    - role: active-server
      when:
        - inventory_hostname == groups[rke2_servers_group_name][0]

#------------------------------------#
- name: Prepare first server node in the cluster
  hosts: k8s_cluster
  become: true
  roles:
    - role: rke-installer
      when:
        - inventory_hostname == groups[rke2_servers_group_name][0]
        - active_server is not defined

#------------------------------------#
- name: Prepare and join remaining nodes of the cluster
  hosts: k8s_cluster
  become: true
  pre_tasks:
    - name: Find Active Server again before joining remaining nodes
      include_role:
        name: active-server
      when:
        - inventory_hostname == groups[rke2_servers_group_name][0]
  roles:
    - role: rke-installer
      when:
        - active_server is defined
        - groups[rke2_cluster_group_name] | length | int >= 2
        - inventory_hostname != active_server

#------------------------------------#
- name: Download Kubeconfig
  hosts: k8s_cluster
  roles:
    - role: kubeconfig
      when:
        - inventory_hostname == groups[rke2_servers_group_name][0]

#------------------------------------#
- name: LVM Manager
  hosts: k8s_cluster
  become: true
  roles:
    - role: lvm-manager
      when:
        - lvm_apply | bool
        - (lvm_workers_only | default(false) | bool == false) or ('workers' in group_names)
